services:
  db:
    image: postgres:16
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ru.practicum.shareit
      POSTGRES_USER: Igor
      POSTGRES_PASSWORD: 12345678